services:
  gmbot:
    build:
      context: .
    container_name: gmbot
    env_file:
      - stack.env
    pull_policy: build
    restart: unless-stopped
    volumes:
      - /opt/docker/gmbot:/data
